[tools]
rojo = { github = "rojo-rbx/rojo", version = "7.4.1" }
stylua = { github = "JohnnyMorganz/StyLua", version = "0.20.0" }
selene = { github = "Kampfkarren/selene", version = "0.27.1" }
wally = { github = "UpliftGames/wally", version = "0.3.2" }
wally-package-types = { github = "JohnnyMorganz/wally-package-types", version = "1.3.1" }
