[package]
name = "pluviolithic/climbing-simulator"
version = "1.0.0"
authors = ["Eric McKanna <ewmckanna@gmail.com>"]
realm = "shared"
registry = "https://github.com/upliftgames/wally-index"

[dependencies]
Sift = "csqrl/sift@0.0.3"
Rodux = "roblox/rodux@3.0.0"
Immut = "solarhorizon/immut@0.4.4"

Red = "red-blox/red@2.0.0"
Guard = "red-blox/guard@1.0.1"
Promise = "evaera/promise@3.1.0"
ZonePlus = "legendoj1/zoneplus@3.2.2"
Janitor = "howmanysmall/janitor@1.13.14"

[server-dependencies]
Cmdr = "evaera/cmdr@1.9.0"
ProfileService = "grilme99/profileservice@1.0.0"
