local RunService = game:GetService("RunService")
local StarterPlayer = game:GetService("StarterPlayer")
local ServerScriptService = game:GetService("ServerScriptService")

-- local producer
--
-- if RunService:IsServer() then
--     producer = require(ServerScriptService.Server.Producer)
-- else
--     producer = require(StarterPlayer.StarterPlayerScripts.Client.Producer)
-- end
--

-- local function selectStats(state: producer.RootState)
-- end
--
-- return {
--     selectStats = selectStats,
-- }
